### ISSUE TITLE
Prefer Framework references for System assemblies

### ISSUE THREAD

**Issue by ChrisRobbers** [launchdarkly/dotnet-client#83] opened 2018-07-18 22:35 UTC
We are trying to update to .NET Framework 4.7.2 and this seems to have exposed an issue caused by the LaunchDarkly .NET Client. There are Nuget references to deprecated System assemblies (System.Net.Http and System.Runtime). Can these be converted to Framework references? This would prevent conflicts on our compilation.

I was able to get it working using [this](https://github.com/dotnet/sdk/issues/2221#issuecomment-386727176) workaround, but it seems a bit hacky (issue is noted by MS [here](https://github.com/Microsoft/dotnet/blob/master/releases/net472/KnownIssues/613745%20-%20Single-name%20references%20are%20removed%20by%20the%20SDK%20when%20targeting%204.7.2.md))

**Comment by eli-darkly** [comment] 2018-07-19 20:17
Could you provide an example of what the proposed change would look like in our .csproj?

**Comment by ChrisRobbers** [comment] 2018-07-19 21:55
Replacing the references with:
```
    <Reference Include="System.Runtime" />
    <Reference Include="System.Net.Http" />
```

**Comment by ChrisRobbers** [comment] 2018-07-27 00:47
Sigh, these framework references are always a giant pain... we've moved on to VS 2017 so I can't repro it, but a few thoughts:

Does the file exist in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.5\Facades`?

Do you absolutely need the references to compile at all?

Have you confirmed the problem on a different machine (to rule out any weirdness with your installation)?

**Comment by eli-darkly** [comment] 2018-07-27 01:37
Thanks for your patience.

1. `System.Runtime.dll` does not exist there. `System.dll` and `System.Net.Http.dll` do.

2. I think we can do without `System.Runtime`, at least. I am able to build and run unit tests without it. I'll make up a new NuGet package without the reference and see if it works any better.

3. It's been reproduced on two machines.

**Comment by eli-darkly** [comment] 2018-07-27 03:08
Looks like removing the System.Runtime reference completely (but keeping the one for System.Net.Http, as a framework reference) is the way to go. Need to do a bit more testing but I hope to have a release out before too long - there are a few other minor changes awaiting release.

**Comment by ChrisRobbers** [comment] 2018-07-27 03:09
Sounds good, thanks for working through that.

**Comment by eli-darkly** [comment] 2018-07-28 00:17
Version 5.2.0 has been released and will be installable whenever NuGet finishes indexing it. Please let us know if that doesn't fix this issue.

**Comment by ChrisRobbers** [comment] 2018-08-02 15:17
Thanks for fixing this! Can you also please fix the [EventSource assembly](https://github.com/launchdarkly/dotnet-eventsource/issues/31) since this one has a dependency on that one as well? Thanks!

**Comment by eli-darkly** [comment] 2018-08-02 21:18
Whoops! Yes, we'll fix that ASAP.

**Comment by eli-darkly** [comment] 2018-08-03 00:04
OK, this has been fixed in EventSource, and the fixed version is used by LaunchDarkly.Client v5.2.2.

**Closed by eli-darkly** 2018-08-03 00:04 UTC
